//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Appointmentid { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
