//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatmant
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Treatment { get; set; }
        public string Note { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
